# Generated by Django 6.0.1 on 2026-01-24 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('#FF6384', 'Red'), ('#36A2EB', 'Blue'), ('#FFCE56', 'Yellow'), ('#4BC0C0', 'Teal'), ('#9966FF', 'Purple'), ('#FF9F40', 'Orange'), ('#7CB342', 'Green'), ('#E91E63', 'Pink'), ('#00BCD4', 'Cyan'), ('#795548', 'Brown'), ('#607D8B', 'Grey'), ('#3F51B5', 'Indigo')], default='#36A2EB', max_length=7)),
                ('icon', models.CharField(choices=[('bi-cart', 'Shopping Cart'), ('bi-house', 'House'), ('bi-car-front', 'Car'), ('bi-cup-hot', 'Food/Drink'), ('bi-lightning', 'Utilities'), ('bi-film', 'Entertainment'), ('bi-heart-pulse', 'Health'), ('bi-mortarboard', 'Education'), ('bi-airplane', 'Travel'), ('bi-gift', 'Gifts'), ('bi-briefcase', 'Work'), ('bi-cash', 'Income'), ('bi-piggy-bank', 'Savings'), ('bi-three-dots', 'Other')], default='bi-three-dots', max_length=50)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('both', 'Both')], default='expense', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
