# Generated by Django 6.0.1 on 2026-01-23 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('wallet', 'Digital Wallet'), ('cash', 'Cash'), ('savings', 'Savings'), ('credit', 'Credit Card')], default='bank', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('icon', models.CharField(choices=[('bi-bank', 'Bank'), ('bi-wallet2', 'Wallet'), ('bi-cash-stack', 'Cash'), ('bi-piggy-bank', 'Savings'), ('bi-credit-card', 'Credit Card'), ('bi-phone', 'Mobile Wallet')], default='bi-wallet2', max_length=50)),
                ('color', models.CharField(choices=[('#28a745', 'Green'), ('#007bff', 'Blue'), ('#ffc107', 'Yellow'), ('#dc3545', 'Red'), ('#6f42c1', 'Purple'), ('#fd7e14', 'Orange'), ('#20c997', 'Teal'), ('#e83e8c', 'Pink')], default='#28a745', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_total', models.BooleanField(default=True, help_text='Include in total balance calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
