# Generated by Django 6.0.1 on 2026-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit limit for credit cards', max_digits=12),
        ),
    ]
